version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      spring:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework.security:*"
      tomcat:
        patterns:
          - "org.apache.tomcat*:*"
          - "org.apache.tomcat.embed:*"